defaults:
  - state: tqg_352x192
  - action: baseline
  - camera: sl_vga15
  - _self_

franka:
  ip: 172.168.0.2
  relative_dynamics_factor: 0.2
  gripper_force: 0.4

rerun: null

inference:
  checkpoint_path: ???
  device: cuda

  state: ${state}
  action: ${action}

  rerun: true
